/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Visual;
import Datos.*;
import javax.swing.table.DefaultTableModel;
import java.awt.Component;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;
/**
 *
 * @author ADMIN
 */
public class FrmBuscarDentista extends javax.swing.JInternalFrame {
    OperacionesConsultorio operacion;

    public void setObj(OperacionesConsultorio operacion) {
        this.operacion = operacion;
    }

    public void cargarCombo() {
        cmbDentista.removeAllItems();
        for (Dentista d : operacion.getListaDentistas()) {
            cmbDentista.addItem(d.getNombreCompleto() + " - " + d.getCi());
        }
    }
    private void ajustarAnchoColumnas(JTable tabla) {
        for (int columna = 0; columna < tabla.getColumnCount(); columna++) {
            int ancho = 50;
            for (int fila = 0; fila < tabla.getRowCount(); fila++) {
                TableCellRenderer renderer =
                        tabla.getCellRenderer(fila, columna);
                Component comp =
                        tabla.prepareRenderer(renderer, fila, columna);
                ancho = Math.max(comp.getPreferredSize().width + 10, ancho);
            }
            tabla.getColumnModel().getColumn(columna).setPreferredWidth(ancho);
        }
    }

    /**
     * Creates new form FrmBuscarDentista
     */
    public FrmBuscarDentista() {
        initComponents();
        this.setFrameIcon(new javax.swing.ImageIcon());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbDentista = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaCitas = new javax.swing.JTable();
        lblCitas = new javax.swing.JLabel();
        lblTratamientos = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaTratamientos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("DR:");

        cmbDentista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnBuscar.setBackground(new java.awt.Color(255, 204, 153));
        btnBuscar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscar.setText("BUSCAR");
        btnBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tablaCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaCitas.setPreferredSize(new java.awt.Dimension(650, 520));
        jScrollPane3.setViewportView(tablaCitas);

        lblCitas.setText("CITAS:");

        lblTratamientos.setText("TRATAMIENTOS:");

        tablaTratamientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaTratamientos.setPreferredSize(new java.awt.Dimension(650, 520));
        jScrollPane4.setViewportView(tablaTratamientos);

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("BUSCAR DENTISTA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(cmbDentista, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCitas)
                                .addGap(115, 115, 115)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblTratamientos)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbDentista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblCitas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(lblTratamientos)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if (operacion.getListaDentistas().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "No hay dentistas registrados");
            return;
        }
        int idx = cmbDentista.getSelectedIndex();
        Dentista dentista = operacion.getListaDentistas().get(idx);

        DefaultTableModel modeloCitas = new DefaultTableModel();
        modeloCitas.addColumn("Paciente");
        modeloCitas.addColumn("Fecha");
        modeloCitas.addColumn("Hora");
        modeloCitas.addColumn("Estado");

        for (Cita c : operacion.getListaCitas()) {
            if (c.getDentista().getCi().equals(dentista.getCi())) {
                modeloCitas.addRow(new Object[]{
                    c.getPaciente().getNombreCompleto(),
                    c.getFecha(), c.getHora(), c.getEstado()
                });
            }
        }
        tablaCitas.setModel(modeloCitas);
        ajustarAnchoColumnas(tablaCitas);

        DefaultTableModel modeloTrat = new DefaultTableModel();
        modeloTrat.addColumn("Paciente");
        modeloTrat.addColumn("Descripcion");
        modeloTrat.addColumn("Costo");
        modeloTrat.addColumn("Fecha");

        for (Paciente p : operacion.getListaPacientes()) {
            for (Tratamiento t : p.getHistorial().getListaTratamientos()) {
                if (t.getDentista() != null &&
                    t.getDentista().getCi().equals(dentista.getCi())) {
                    modeloTrat.addRow(new Object[]{
                        p.getNombreCompleto(),
                        t.getDescripcion(), t.getCosto(), t.getFecha()
                    });
                }
            }
        }
        tablaTratamientos.setModel(modeloTrat);
        ajustarAnchoColumnas(tablaTratamientos);

        if (modeloCitas.getRowCount() == 0 && modeloTrat.getRowCount() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Este dentista no tiene citas ni tratamientos registrados");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> cmbDentista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblCitas;
    private javax.swing.JLabel lblTratamientos;
    private javax.swing.JTable tablaCitas;
    private javax.swing.JTable tablaTratamientos;
    // End of variables declaration//GEN-END:variables
}
