/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;

import Datos.OperacionesConsultorio;
import javax.swing.JFrame;
/**
 *
 * @author ADMIN
 */
public class MenuPrincipal extends javax.swing.JFrame {
    OperacionesConsultorio operacion;
    
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {   
        initComponents();
        operacion = new OperacionesConsultorio();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        this.setMinimumSize(new java.awt.Dimension(1024, 700));  
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new Visual.DesktopConFondo();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        registrarPacienteItem = new javax.swing.JMenuItem();
        mostrarPacienteItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        registrarDentistaItem = new javax.swing.JMenuItem();
        mostrarDentistaItem = new javax.swing.JMenuItem();
        eliminarDentista = new javax.swing.JMenuItem();
        buscarDentistaItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        registrarTratamientoItem = new javax.swing.JMenuItem();
        verHistorialItem = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        registrarPagoItem = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        registrarCitaItem = new javax.swing.JMenuItem();
        mostrarCitaItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Paciente");

        registrarPacienteItem.setText("Registrar Paciente");
        registrarPacienteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarPacienteItemActionPerformed(evt);
            }
        });
        jMenu1.add(registrarPacienteItem);

        mostrarPacienteItem.setText("Mostrar Paciente");
        mostrarPacienteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarPacienteItemActionPerformed(evt);
            }
        });
        jMenu1.add(mostrarPacienteItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Dentista");

        registrarDentistaItem.setText("Registrar Dentista");
        registrarDentistaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarDentistaItemActionPerformed(evt);
            }
        });
        jMenu2.add(registrarDentistaItem);

        mostrarDentistaItem.setText("Mostrar Dentista");
        mostrarDentistaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarDentistaItemActionPerformed(evt);
            }
        });
        jMenu2.add(mostrarDentistaItem);

        eliminarDentista.setText("Eliminar Dentista");
        eliminarDentista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarDentistaActionPerformed(evt);
            }
        });
        jMenu2.add(eliminarDentista);

        buscarDentistaItem.setText("Buscar Dentista");
        buscarDentistaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarDentistaItemActionPerformed(evt);
            }
        });
        jMenu2.add(buscarDentistaItem);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Tratamientos");

        registrarTratamientoItem.setText("Registrar Tratamiento");
        registrarTratamientoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarTratamientoItemActionPerformed(evt);
            }
        });
        jMenu3.add(registrarTratamientoItem);

        verHistorialItem.setText("Ver Historial");
        verHistorialItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verHistorialItemActionPerformed(evt);
            }
        });
        jMenu3.add(verHistorialItem);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Pagos");

        registrarPagoItem.setText("Registrar Pago");
        registrarPagoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarPagoItemActionPerformed(evt);
            }
        });
        jMenu4.add(registrarPagoItem);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Citas");

        registrarCitaItem.setText("Registrar Cita");
        registrarCitaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarCitaItemActionPerformed(evt);
            }
        });
        jMenu5.add(registrarCitaItem);

        mostrarCitaItem.setText("Mostrar Citas");
        mostrarCitaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarCitaItemActionPerformed(evt);
            }
        });
        jMenu5.add(mostrarCitaItem);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarPacienteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarPacienteItemActionPerformed
        // TODO add your handling code here:
        FrmListaPacientes frm = new FrmListaPacientes();
        frm.setObj(operacion);
        frm.cargarDatos();
        escritorio.add(frm);
        frm.setVisible(true);
        frm.setLocation(
            (escritorio.getWidth() - frm.getWidth()) / 2,
            (escritorio.getHeight() - frm.getHeight()) / 2
        );
        frm.moveToFront();
        try {
            frm.setSelected(true);
        } catch (java.beans.PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_mostrarPacienteItemActionPerformed

    private void registrarPacienteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarPacienteItemActionPerformed
        // TODO add your handling code here:
        FrmPaciente frm = new FrmPaciente();
        frm.setObj(operacion);
        escritorio.add(frm);
        frm.setVisible(true);
        frm.setLocation(
            (escritorio.getWidth() - frm.getWidth()) / 2,
            (escritorio.getHeight() - frm.getHeight()) / 2
        );
        frm.moveToFront();
        try {
            frm.setSelected(true);
        } catch (java.beans.PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_registrarPacienteItemActionPerformed

    private void registrarDentistaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarDentistaItemActionPerformed
        // TODO add your handling code here:
        FrmDentista frm = new FrmDentista();
        frm.setObj(operacion);
        escritorio.add(frm);
        frm.setVisible(true);
        frm.setLocation(
            (escritorio.getWidth() - frm.getWidth()) / 2,
            (escritorio.getHeight() - frm.getHeight()) / 2
        );
        frm.moveToFront();
        try {
            frm.setSelected(true);
        } catch (java.beans.PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_registrarDentistaItemActionPerformed

    private void mostrarDentistaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarDentistaItemActionPerformed
        // TODO add your handling code here:
        FrmListaDentistas frm = new FrmListaDentistas();
        frm.setObj(operacion);
        frm.cargarDatos();
        escritorio.add(frm);
        frm.setVisible(true);
        frm.setLocation(
            (escritorio.getWidth() - frm.getWidth()) / 2,
            (escritorio.getHeight() - frm.getHeight()) / 2
        );
        frm.moveToFront();
        try {
            frm.setSelected(true);
        } catch (java.beans.PropertyVetoException ex) {
            ex.printStackTrace();
        } 
    }//GEN-LAST:event_mostrarDentistaItemActionPerformed

    private void registrarTratamientoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarTratamientoItemActionPerformed
        // TODO add your handling code here:
        FrmTratamiento frm = new FrmTratamiento();
        frm.setObj(operacion);
        frm.cargarCombos();
        escritorio.add(frm);
        frm.setVisible(true);
        frm.setLocation(
            (escritorio.getWidth() - frm.getWidth()) / 2,
            (escritorio.getHeight() - frm.getHeight()) / 2
        );
        frm.moveToFront();
        try {
            frm.setSelected(true);
        } catch (java.beans.PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_registrarTratamientoItemActionPerformed

    private void verHistorialItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verHistorialItemActionPerformed
        // TODO add your handling code here:
        FrmHistorial frm = new FrmHistorial();
        frm.setObj(operacion);
        frm.cargarCombo();
        escritorio.add(frm);
        frm.setVisible(true);
        frm.setLocation(
            (escritorio.getWidth() - frm.getWidth()) / 2,
            (escritorio.getHeight() - frm.getHeight()) / 2
        );
        frm.moveToFront();
        try {
            frm.setSelected(true);
        } catch (java.beans.PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_verHistorialItemActionPerformed

    private void registrarPagoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarPagoItemActionPerformed
        // TODO add your handling code here:
        FrmPago frm = new FrmPago();
        frm.setObj(operacion);
        frm.cargarCombo();
        escritorio.add(frm);
        frm.setVisible(true);
        frm.setLocation(
            (escritorio.getWidth() - frm.getWidth()) / 2,
            (escritorio.getHeight() - frm.getHeight()) / 2
        );
        frm.moveToFront();
        try {
            frm.setSelected(true);
        } catch (java.beans.PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_registrarPagoItemActionPerformed

    private void registrarCitaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarCitaItemActionPerformed
        // TODO add your handling code here:
        FrmCita frm = new FrmCita();
        frm.setObj(operacion);
        frm.cargarCombos();
        escritorio.add(frm);
        frm.setVisible(true);
        frm.setLocation(
            (escritorio.getWidth() - frm.getWidth()) / 2,
            (escritorio.getHeight() - frm.getHeight()) / 2
        );
        frm.moveToFront();
        try {
            frm.setSelected(true);
        } catch (java.beans.PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_registrarCitaItemActionPerformed

    private void mostrarCitaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarCitaItemActionPerformed
        // TODO add your handling code here:
        FrmListaCitas frm = new FrmListaCitas();
        frm.setObj(operacion);
        frm.cargarDatos();
        escritorio.add(frm);
        frm.setVisible(true);
        frm.setLocation(
            (escritorio.getWidth() - frm.getWidth()) / 2,
            (escritorio.getHeight() - frm.getHeight()) / 2
        );
        frm.moveToFront();
        try {
            frm.setSelected(true);
        } catch (java.beans.PropertyVetoException ex) {
            ex.printStackTrace();
        } 
    }//GEN-LAST:event_mostrarCitaItemActionPerformed

    private void eliminarDentistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarDentistaActionPerformed
        // TODO add your handling code here:
        FrmEliminarDentista frm = new FrmEliminarDentista();
        frm.setObj(operacion);
        frm.cargarCombo();
        escritorio.add(frm);
        frm.setVisible(true);
        frm.setLocation(
            (escritorio.getWidth() - frm.getWidth()) / 2,
            (escritorio.getHeight() - frm.getHeight()) / 2
        );
        frm.moveToFront();
        try {
            frm.setSelected(true);
        } catch (java.beans.PropertyVetoException ex) {
            ex.printStackTrace();
        }         
    }//GEN-LAST:event_eliminarDentistaActionPerformed

    private void buscarDentistaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarDentistaItemActionPerformed
        // TODO add your handling code here:
        FrmBuscarDentista frm = new FrmBuscarDentista();
        frm.setObj(operacion);
        frm.cargarCombo();
        escritorio.add(frm);
        frm.setVisible(true);
        frm.setLocation(
            (escritorio.getWidth() - frm.getWidth()) / 2,
            (escritorio.getHeight() - frm.getHeight()) / 2
        );
        frm.moveToFront();
        try {
            frm.setSelected(true);
        } catch (java.beans.PropertyVetoException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_buscarDentistaItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem buscarDentistaItem;
    private javax.swing.JMenuItem eliminarDentista;
    private Visual.DesktopConFondo escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mostrarCitaItem;
    private javax.swing.JMenuItem mostrarDentistaItem;
    private javax.swing.JMenuItem mostrarPacienteItem;
    private javax.swing.JMenuItem registrarCitaItem;
    private javax.swing.JMenuItem registrarDentistaItem;
    private javax.swing.JMenuItem registrarPacienteItem;
    private javax.swing.JMenuItem registrarPagoItem;
    private javax.swing.JMenuItem registrarTratamientoItem;
    private javax.swing.JMenuItem verHistorialItem;
    // End of variables declaration//GEN-END:variables
}
